Update esy.json
Change the scripts so they run. `esy buildDev` or `esy x buildDev` still gets you: 

```sh
mando@mandalarian ~/G/s/sorting-in-reason [1]> esy x buildDev
error: unable to resolve command: buildDev

esy: exiting due to errors above
mando@mandalarian ~/G/s/sorting-in-reason [1]> esy buildDev
error: unable to resolve command: buildDev
```